ALTER TABLE EPISODE
    ADD CONSTRAINT FK_EPISODE_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id)  ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE EARNS
    ADD CONSTRAINT FK_EARNS_SERVICE_ID
        FOREIGN KEY (service_id) REFERENCES SERVICE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE EARNS
    ADD CONSTRAINT FK_EARNS_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE HOST_PAY
    ADD CONSTRAINT FK_HOST_PAY_SERVICE_ID
        FOREIGN KEY (service_id) REFERENCES SERVICE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE HOST_PAY
    ADD CONSTRAINT FK_HOST_PAY_HOST_ID
        FOREIGN KEY (host_id) REFERENCES HOST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE RL_PAY
    ADD CONSTRAINT FK_RL_PAY_SERVICE_ID
        FOREIGN KEY (service_id) REFERENCES SERVICE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE RL_PAY
    ADD CONSTRAINT FK_RL_PAY_RECORD_LABEL_ID
        FOREIGN KEY (record_label_id) REFERENCES RECORD_LABEL(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE COMPILES
    ADD CONSTRAINT FK_COMPILES_ARTIST_ID
        FOREIGN KEY (artist_id) REFERENCES ARTIST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE COMPILES
    ADD CONSTRAINT FK_COMPILES_ALBUM_ID
        FOREIGN KEY (album_id) REFERENCES ALBUM(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE CREATES
    ADD CONSTRAINT FK_CREATES_ARTIST_ID
        FOREIGN KEY (artist_id) REFERENCES ARTIST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE CREATES
    ADD CONSTRAINT FK_CREATES_SONG_ID
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE SONG_ALBUM
    ADD CONSTRAINT FK_SONG_ALBUM_SONG_ID
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE SONG_ALBUM
    ADD CONSTRAINT FK_SONG_ALBUM_ALBUM_ID
        FOREIGN KEY (album_id) REFERENCES ALBUM(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE SONG_ALBUM
    ADD CONSTRAINT UNIQUE_SONG_ID
        UNIQUE (song_id);

/*----------------------------------------------------------*/

ALTER TABLE SONG_GENRE
    ADD CONSTRAINT FK_SONG_GENRE_SONG_ID
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE SONG_GENRE
    ADD CONSTRAINT FK_SONG_GENRE_GENRE_ID1
        FOREIGN KEY (genre_id) REFERENCES GENRE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE OWNS
    ADD CONSTRAINT FK_OWNS_RECORD_LABEL_ID
        FOREIGN KEY (record_label_id) REFERENCES RECORD_LABEL(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE OWNS
    ADD CONSTRAINT FK_OWNS_SONG_ID
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE SONG_LISTEN
    ADD CONSTRAINT FK_SONG_LISTEN_SONG_ID
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE SONG_LISTEN
    ADD CONSTRAINT FK_SONG_LISTEN_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE SIGNS
    ADD CONSTRAINT FK_SIGNS_ARTIST_ID
        FOREIGN KEY (artist_id) REFERENCES ARTIST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE SIGNS
    ADD CONSTRAINT FK_SIGNS_RECORD_LABEL_ID
        FOREIGN KEY (record_label_id) REFERENCES RECORD_LABEL(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE PODCAST_HOST
    ADD CONSTRAINT FK_PODCAST_HOST_HOST_ID
        FOREIGN KEY (host_id) REFERENCES HOST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE PODCAST_HOST
    ADD CONSTRAINT FK_PODCAST_HOST_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE PODCAST_EP_LISTEN
    ADD CONSTRAINT FK_PODCAST_EP_LISTEN_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE PODCAST_EP_LISTEN
    ADD CONSTRAINT FK_PODCAST_EP_LISTEN_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE PODCAST_SPONSOR
    ADD CONSTRAINT FK_PODCAST_SPONSOR_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE PODCAST_SPONSOR
    ADD CONSTRAINT FK_PODCAST_SPONSOR_SPONSOR_ID
        FOREIGN KEY (sponsor_id) REFERENCES SPONSOR(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE EPISODE_GUEST
    ADD CONSTRAINT FK_EPISODE_GUEST_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE EPISODE_GUEST
    ADD CONSTRAINT FK_EPISODE_GUEST_GUEST_ID
        FOREIGN KEY (guest_id) REFERENCES GUEST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE PODCAST_GENRE
    ADD CONSTRAINT FK_PODCAST_GENRE_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE PODCAST_GENRE
    ADD CONSTRAINT FK_PODCAST_GENRE_GENRE_ID
        FOREIGN KEY (genre_id) REFERENCES GENRE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE ARTIST_IS
    ADD CONSTRAINT FK_ARTIST_IS_ARTIST_ID
        FOREIGN KEY (artist_id) REFERENCES ARTIST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE ARTIST_IS
    ADD CONSTRAINT FK_ARTIST_IS_ARTIST_TYPE_ID
        FOREIGN KEY (artist_type_id) REFERENCES ARTIST_TYPE(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE RATES
    ADD CONSTRAINT FK_RATES_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE RATES
    ADD CONSTRAINT FK_RATES_PODCAST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;


/*----------------------------------------------------------*/

ALTER TABLE ARTIST_SUBSCRIPTION
    ADD CONSTRAINT FK_ARTIST_SUBSCRIPTION_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE ARTIST_SUBSCRIPTION
    ADD CONSTRAINT FK_ARTIST_SUBSCRIPTION_ARTIST_ID
        FOREIGN KEY (artist_id) REFERENCES ARTIST(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE ARTIST_SUBSCRIPTION
    ADD CONSTRAINT AS_UPDATE_TIME_MORE_THAN_CREATED_TIME
        CHECK ( updated_at >= created_at ) ;

/*----------------------------------------------------------*/

ALTER TABLE PODCAST_SUBSCRIPTION
    ADD CONSTRAINT FK_PODCAST_SUBSCRIPTION_USER_ID
        FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE PODCAST_SUBSCRIPTION
    ADD CONSTRAINT FK_PODCAST_SUBSCRIPTION_ARTIST_ID
        FOREIGN KEY (podcast_id) REFERENCES PODCAST(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE PODCAST_SUBSCRIPTION
    ADD CONSTRAINT PS_UPDATE_TIME_MORE_THAN_CREATED_TIME
        CHECK ( updated_at >= created_at ) ;

/*----------------------------------------------------------*/
#
# ALTER TABLE COMPILES ADD CONSTRAINT CHECK_VALID_ARTIST
#     CHECK( EXISTS (SELECT C.artist_id FROM  manand.CREATES C, manand.SONG_ALBUM SA WHERE C.song_id = SA.song_id AND COMPILES.album_id = SA.album_id AND COMPILES.artist_id = C.artist_id));

ALTER TABLE HISTORICAL_SONG_PLAY_COUNT
    ADD CONSTRAINT FK_HS_S_PL_CNT
        FOREIGN KEY (song_id) REFERENCES SONG(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE HISTORICAL_EPISODE_PLAY_COUNT
    ADD CONSTRAINT FK_HS_E_PL_CNT
        FOREIGN KEY (podcast_id, episode_num) REFERENCES EPISODE(podcast_id, episode_num) ON DELETE CASCADE ON UPDATE CASCADE ;