# This file identifies the order of inserts ( -- means data is inserted)
# SPONSOR
# GUEST
# GENRE --
# HOST
# ALBUM --
# SONG --
# ARTIST --
# RECORD_LABEL --
# USER
# SERVICE --
# PODCAST
# RATES
# ARTIST_TYPE
# ARTIST_IS
# PRIMARY_GENRE
# PODCAST_GENRE
# EPISODE
# EPISODE_GUEST
# PODCAST_SPONSOR
# PODCAST_EP_LISTEN
# PODCAST_HOST
# PODCAST_SUBSCRIPTION
# ARTIST_SUBSCRIPTION
# SIGNS --
# SONG_LISTEN
# OWNS --
# SONG_GENRE
# SONG_ALBUM --
# CREATES --
# COMPILES --
# EARNS
# RL_PAY
# HOST_PAY
# ARTIST_PAY


select * from SONG;